import { SellerProfileData } from "@/lib/investigation/sellerProfile";
import { LensInvestigationData } from "@/lib/investigation/productLens";
import { PriceComparisonData } from "@/lib/investigation/priceComparison";
import { SellerReputationData } from "@/lib/investigation/sellerReputation";

/**
 * Generic Investigation Check Status and Contract
 */
export type CheckStatus =
  | "success"
  | "no_results"
  | "failed"
  | "not_run";

export interface CheckResult<T> {
  status: CheckStatus;
  data: T | null;
  message?: string;
  timestamp?: string;
  source?: string;
}

/**
 * Top-level structured evidence aggregated across all 4 checks
 */
export interface InvestigationEvidence {
  sellerProfile: CheckResult<SellerProfileData>;
  imageMatches: CheckResult<LensInvestigationData>;
  priceComparison: CheckResult<PriceComparisonData>;
  reputationSearch: CheckResult<SellerReputationData>;
  targetContext: {
    sellerHandle: string;
    productName?: string;
    quotedPrice?: string;
    previewUrl?: string | null;
  };
  executedAt: string;
}

/**
 * Key Finding Item for Section 01
 */
export interface KeyFindingItem {
  category: "price" | "optical" | "profile" | "reputation";
  title: string;
  detail: string;
  severity: "neutral" | "info" | "warning";
}

/**
 * Checklist Item for Section 06
 */
export interface SafetyChecklistItem {
  id: string;
  stepNumber: number;
  title: string;
  recommendation: string;
  reason: string;
}

/**
 * Structured AI Synthesis output generated by local Ollama (Gemma 3 4B)
 */
export interface AIReportSynthesis {
  executiveSummary: string;
  trustVerdictLevel?: "clean" | "caution" | "elevated_risk";
  trustVerdictTitle?: string;
  bottomLineRecommendation?: string;
  keyFindings: KeyFindingItem[];
  checklist: SafetyChecklistItem[];
  evidenceGrounded: boolean;
  modelUsed: string;
  generatedAt: string;
}
